[tool.poetry]
name = "nvidia-rag-canonical"
version = "0.1.0"
description = "RAG with NVIDIA"
authors = ["Sagar Bogadi Manjunath <sbogadimanju@nvidia.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.325"
pymilvus = ">=2.3.0"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "nvidia_rag_canonical"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["Milvus"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
